# Generated by Django 5.0.3 on 2024-03-24 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBuy', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImg', models.TextField()),
                ('productName', models.CharField(max_length=120)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('productQnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cartFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carthistory')),
                ('productFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
    ]
